# -*- coding: utf-8 -*-
"""spam email detection using logistic reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-w7Dsa9Jah9c2GAJj_ELsZv_Ao17TLV9
"""

#Import libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#data declaration
emails = [    "Congratulations You have won a 1000 dollar gift card click here to claim",
    "Act now Limited time offer only for selected recipients",
    "Urgent Your account will be suspended unless you verify immediately",
    "Just checking in to confirm our lunch reservation tomorrow",
    "We appreciate your feedback and will get back to you shortly",
    "Win big prizes by clicking this link now",
    "Please review the attached invoice for your recent purchase",
    "Limited offer Buy one get one free",
    "Are you available for a meeting next week",
    "Your subscription will expire soon please renew"
]
labels = [1, 1, 1, 0, 0, 1, 0, 1, 0, 0]

# convert text to numbers
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)

# training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.3, random_state=42)

# model training
model = LogisticRegression()
model.fit(X_train, y_train)

# predict based on test data
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model accuracy on test data:",accuracy)
counts = np.bincount(y_pred)

#get user input
user_input = input("Enter a email text to predict: ").strip()
user_vec = vectorizer.transform([user_input])
prediction = model.predict(user_vec)[0]
result = "spam" if prediction == 1 else "not spam"
print("Prediction:", result)

# visualization
labels_names = ['Not Spam', 'Spam']
plt.bar(labels_names, counts, color=['blue', 'orange'])
plt.title('Predicted Email Class Counts')
plt.ylabel('Number of Emails')
plt.show()